version: '3.8'
services:
  app:
    image: node:16-alpine
    expose:
      - 6000
    depends_on:
      - mysqldb
    container_name: "lottery_app"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    command: npm start
    ports:
      - 3001:3001
    environment:
      DB_HOST: mysqldb
      DB_PORT: '3306'
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'adminpw'
      DB_DATABASE: 'lottery'
      NODE_DOCKER_PORT: '3001'
    networks:
      - app-network
  mysqldb:
    image: mysql
    expose:
      - 3306
    container_name: 'lottery-db'
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: "rootpw"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "adminpw"
      MYSQL_DATABASE: "lottery"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysqldata:

